server:
  port: 8081

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://projectdb:3306/projects_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      task-service:
        url: http://task-service:8082
