
pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        DOCKER_HUB_REPO = 'imane1233333333333333/construction'
        DOCKER_IMAGE = 'constructionxpert'
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
        DOCKER_CREDENTIALS_ID = 'docker-credentials-id'
        SONARQUBE = 'SonarQubeServer'
        SONARQUBE_TOKEN = credentials('SonarQubeToken')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/imane-el-mazouz/constructionxpert-backend.git'
            }
        }

        stage('Build and Test') {
            steps {
                dir('ConstructionXpert') {
                    bat 'mvn clean install'
                    bat 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('ConstructionXpert') {
                    withSonarQubeEnv(SONARQUBE) {
                        bat "mvn sonar:sonar -Dsonar.token=${SONARQUBE_TOKEN}"
                    }
                }
            }
        }

       stage('Build Docker Images') {
            steps {
                script {
                    def services = ['eureka-server', 'gateway-service', 'project-service', 'resource-service', 'task-service', 'user-service']

                    dir('ConstructionXpert') {
                        services.each { service ->
                            dir(service) {
                                bat "docker build -t constructionxpert-${service} ."
                            }
                        }
                    }
                }
            }
        }


        stage('Quality Gate Check') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

     stage('Tag and Push Docker Images') {
            steps {
                script {
                    def services = ['eureka-server', 'gateway-service', 'project-service', 'resource-service', 'task-service', 'user-service']

                    docker.withRegistry("https://index.docker.io/v1/", 'docker-credentials-id') {
                        services.each { service ->
                            def imageName = "${DOCKER_HUB_REPO}:${service}"
                            bat """
                                docker tag constructionxpert-${service}:latest ${imageName}
                                docker push ${imageName}
                            """
                        }
                    }
                }
            }
        }
        stage('Run Docker Compose') {
            steps {
                script {
                    dir('ConstructionXpert') {
                        bat 'docker-compose up -d'
                    }
                }
            }
        }
    }



    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
